const MONGODB_PASSWD = Bun.env.MONGODB_PASSWD;
const MONGODB_USER = Bun.env.MONGODB_USER;
const MONGODB_CLUSTER = Bun.env.MONGODB_CLUSTER;
const PORT = Bun.env.PORT;

export const envs = { MONGODB_CLUSTER, MONGODB_USER, MONGODB_PASSWD, PORT };
